repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check --fix
        entry: python3 -m ruff check --fix .
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: python3 -m ruff format .
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy src
        entry: python3 -m mypy src
        language: system
        pass_filenames: false

      - id: bandit
        name: bandit src scripts
        entry: python3 -m bandit -q --severity-level medium --confidence-level medium -c pyproject.toml -r src scripts
        language: system
        pass_filenames: false
